# Generated by Django 4.2.1 on 2023-09-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='imgae',
            new_name='image',
        ),
    ]
