# Generated by Django 4.2.1 on 2023-09-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transations', '0002_alter_transations_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transations',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
