# Generated by Django 4.2.1 on 2023-09-25 06:37

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('transations', '0003_alter_transations_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transations',
            name='transaction_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=25, prefix='TRN', unique=True),
        ),
    ]
