# Generated by Django 4.2.1 on 2023-09-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transations', '0004_alter_transations_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transations',
            old_name='receiver_amount',
            new_name='receiver_account',
        ),
        migrations.RenameField(
            model_name='transations',
            old_name='sender_amount',
            new_name='sender_account',
        ),
    ]
